/*==================================================
                SENKU PAY
              ADMIN KYC REVIEW
==================================================*/
document.addEventListener("DOMContentLoaded",async()=>{
const API_BASE_URL="https://senkupay-api.onrender.com";
const USERS_ENDPOINT=`${API_BASE_URL}/api/admin/users`;
const token=sessionStorage.getItem("adminToken")||localStorage.getItem("adminToken");
function logout(){["adminToken","currentAdmin","currentUser","adminRememberDevice"].forEach(k=>{sessionStorage.removeItem(k);localStorage.removeItem(k)});window.location.href="admin-login.html"}
if(!token){logout();return}
const $=id=>document.getElementById(id);
const els={table:$("kycTable"),search:$("kycSearch"),status:$("kycStatusFilter"),sort:$("kycSort"),refresh:$("refreshKycButton"),message:$("kycPageMessage"),pending:$("pendingKycCount"),verified:$("verifiedKycCount"),rejected:$("rejectedKycCount"),reverify:$("reverifyKycCount"),results:$("kycResultsText"),page:$("kycPageText"),prev:$("kycPreviousPage"),next:$("kycNextPage"),sync:$("lastKycSync"),modal:$("kycReviewModal"),close:$("closeKycReview"),reviewMessage:$("reviewMessage"),documents:$("reviewDocuments"),note:$("adminReviewNote"),reason:$("reviewReason"),imageModal:$("kycImageModal"),largeImage:$("kycLargeImage"),original:$("openKycOriginal"),imageClose:$("closeKycImage"),sidebar:$("adminSidebar"),overlay:$("adminSidebarOverlay"),menu:$("adminMobileMenuButton"),logout:$("adminLogoutButton")};
let records=[],filtered=[],selected=null,currentPage=1;const pageSize=10;
const esc=v=>String(v??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;");
const fmtDate=v=>{if(!v)return"--";const d=new Date(v);return Number.isNaN(d.getTime())?"--":d.toLocaleString()};
const normalizeStatus=v=>String(v||"NOT_SUBMITTED").trim().toLowerCase().replaceAll(" ","_").replaceAll("-","_");
const statusLabel=v=>normalizeStatus(v).replaceAll("_"," ").replace(/\b\w/g,c=>c.toUpperCase());
function showMessage(text,type="info",target=els.message){if(!target)return;target.hidden=false;target.className=target===els.message?`page-message show ${type}`:`modal-message show ${type}`;target.textContent=text}
function hideMessage(target=els.message){if(!target)return;target.hidden=true;target.className=target===els.message?"page-message":"modal-message";target.textContent=""}
async function api(url,options={}){const r=await fetch(url,{...options,headers:{Accept:"application/json",Authorization:`Bearer ${token}`,...(options.body?{"Content-Type":"application/json"}:{}),...(options.headers||{})}});if(r.status===401||r.status===403){logout();throw new Error("Administrator session expired.")}const ct=r.headers.get("content-type")||"";const d=ct.includes("application/json")?await r.json():{message:await r.text()};if(!r.ok)throw new Error(d.message||d.error||"Admin request failed.");return d}
function userList(data){const x=Array.isArray(data)?data:data.users||data.data||data.results||[];return Array.isArray(x)?x:[]}
function kycObject(data){return data.kyc||data.verification||data.kycVerification||data.data?.kyc||data.data?.verification||data.data||data||null}
function normalizeRecord(user,data){const k=kycObject(data)||{};const docs=Array.isArray(k.documents)?k.documents:Array.isArray(data?.documents)?data.documents:[];return{userId:user.id||user.userId,userName:user.username||user.fullName||user.name||"User",email:user.email||"No email",joined:user.createdAt||user.registeredAt,status:normalizeStatus(k.status||user.kycStatus),documentType:k.documentType||k.document_type||"--",country:k.documentCountry||k.documentCountryCode||k.issuingCountry||k.country||"--",submittedAt:k.submittedAt||k.submitted_at,verifiedAt:k.verifiedAt||k.reviewedAt,source:k.source||"--",documents:docs,rejectionReason:k.rejectionReason||"",reverificationReason:k.reverificationReason||"",adminNote:k.adminNote||"",raw:k}}
async function load(){hideMessage();els.table.innerHTML='<tr class="loading-row"><td colspan="6"><i class="fa-solid fa-spinner fa-spin"></i> Loading KYC submissions...</td></tr>';els.refresh.disabled=true;els.refresh.classList.add("loading");try{const users=userList(await api(USERS_ENDPOINT));const list=await Promise.all(users.map(async u=>{try{return normalizeRecord(u,await api(`${USERS_ENDPOINT}/${encodeURIComponent(u.id||u.userId)}/kyc`))}catch(e){if(/not found|not submitted|404/i.test(e.message))return normalizeRecord(u,{status:"NOT_SUBMITTED"});console.warn("KYC load failed for",u.id,e);return normalizeRecord(u,{status:u.kycStatus||"NOT_SUBMITTED",loadError:e.message})}}));records=list;updateStats();applyFilters();els.sync.textContent=`Last synchronized ${new Date().toLocaleString()}`;}catch(e){console.error(e);els.table.innerHTML='<tr class="loading-row"><td colspan="6">Unable to load KYC records.</td></tr>';showMessage(e.message||"Unable to load KYC records.","error")}finally{els.refresh.disabled=false;els.refresh.classList.remove("loading")}}
function updateStats(){const count=s=>records.filter(r=>normalizeStatus(r.status)===s).length;els.pending.textContent=count("pending");els.verified.textContent=count("verified")+count("approved");els.rejected.textContent=count("rejected");els.reverify.textContent=count("reverification_required")+count("reverify_required")}
function applyFilters(){const q=(els.search.value||"").trim().toLowerCase(),st=els.status.value;filtered=records.filter(r=>{const hay=[r.userId,r.userName,r.email,r.documentType,r.country,r.status].join(" ").toLowerCase();return(!q||hay.includes(q))&&(st==="all"||normalizeStatus(r.status)===st)});if(els.sort.value==="newest")filtered.sort((a,b)=>new Date(b.submittedAt||0)-new Date(a.submittedAt||0));if(els.sort.value==="oldest")filtered.sort((a,b)=>new Date(a.submittedAt||0)-new Date(b.submittedAt||0));if(els.sort.value==="user")filtered.sort((a,b)=>a.userName.localeCompare(b.userName));currentPage=1;render()}
function render(){const pages=Math.max(1,Math.ceil(filtered.length/pageSize));currentPage=Math.min(currentPage,pages);const start=(currentPage-1)*pageSize,page=filtered.slice(start,start+pageSize);if(!page.length){els.table.innerHTML='<tr class="loading-row"><td colspan="6"><i class="fa-solid fa-id-card"></i> No KYC records match the current filters.</td></tr>'}else els.table.innerHTML=page.map(r=>`<tr><td><div class="user-cell"><div class="user-avatar">${esc(r.userName.charAt(0).toUpperCase())}</div><div><strong>${esc(r.userName)}</strong><span>${esc(r.email)}</span></div></div></td><td>${esc(r.documentType)}</td><td>${esc(r.country)}</td><td>${esc(fmtDate(r.submittedAt))}</td><td><span class="kyc-status ${esc(normalizeStatus(r.status))}">${esc(statusLabel(r.status))}</span></td><td><button class="review-button" data-id="${esc(r.userId)}"><i class="fa-solid fa-eye"></i> Review</button></td></tr>`).join("");els.results.textContent=filtered.length?`Showing ${start+1}-${Math.min(start+page.length,filtered.length)} of ${filtered.length} records`:"Showing 0 records";els.page.textContent=`Page ${currentPage} of ${pages}`;els.prev.disabled=currentPage<=1;els.next.disabled=currentPage>=pages}
function docName(d){return String(d.type||d.documentType||"Document").replaceAll("_"," ").replace(/\b\w/g,c=>c.toUpperCase())}
function docUrl(d){return d.fileUrl||d.url||d.secureUrl||d.documentUrl||""}
function openReview(id){selected=records.find(r=>String(r.userId)===String(id));if(!selected)return;hideMessage(els.reviewMessage);els.note.value=selected.adminNote||"";els.reason.value=selected.rejectionReason||selected.reverificationReason||"";$("reviewAvatar").textContent=selected.userName.charAt(0).toUpperCase();$("reviewUserName").textContent=selected.userName;$("reviewUserEmail").textContent=selected.email;$("reviewUserId").textContent=selected.userId||"--";$("reviewDocumentType").textContent=selected.documentType;$("reviewCountry").textContent=selected.country;$("reviewSubmitted").textContent=fmtDate(selected.submittedAt);$("reviewVerified").textContent=fmtDate(selected.verifiedAt);$("reviewSource").textContent=selected.source;const badge=$("reviewStatus");badge.className=`kyc-status ${normalizeStatus(selected.status)}`;badge.textContent=statusLabel(selected.status);els.documents.innerHTML=selected.documents.length?selected.documents.map((d,i)=>{const url=docUrl(d);const image=/^image\//i.test(d.mimeType||"")||/\.(png|jpe?g|webp|gif)(\?|$)/i.test(url);return`<button class="document-card" data-url="${esc(url)}" ${url?"":"disabled"}>${image&&url?`<img src="${esc(url)}" alt="${esc(docName(d))}">`:`<div class="file-icon"><i class="fa-solid fa-file-shield"></i></div>`}<div><strong>${esc(docName(d))}</strong><span>${esc(d.fileName||`Document ${i+1}`)}</span></div></button>`}).join(""):'<div class="no-documents"><i class="fa-solid fa-file-circle-xmark"></i><p>No uploaded documents were returned by the backend.</p></div>';els.modal.classList.add("active");els.modal.setAttribute("aria-hidden","false");document.body.classList.add("modal-open")}
function closeReview(){els.modal.classList.remove("active");els.modal.setAttribute("aria-hidden","true");document.body.classList.remove("modal-open");selected=null}
async function action(type,button){if(!selected)return;const reason=els.reason.value.trim(),note=els.note.value.trim();if(["reject","reverify","revoke"].includes(type)&&!reason){showMessage("Enter a reason before performing this action.","error",els.reviewMessage);els.reason.focus();return}const labels={approve:"Approve",reject:"Reject",reverify:"Request reverification","offline-verify":"Offline verify",revoke:"Revoke"};if(!confirm(`${labels[type]} KYC for ${selected.userName}?`))return;button.disabled=true;button.classList.add("loading");try{const body={note,adminNote:note,reason,rejectionReason:reason,reverificationReason:reason};await api(`${USERS_ENDPOINT}/${encodeURIComponent(selected.userId)}/kyc/${type}`,{method:"POST",body:JSON.stringify(body)});showMessage(`KYC action completed: ${labels[type]}.`,"success",els.reviewMessage);await load();const updated=records.find(r=>String(r.userId)===String(selected?.userId));if(updated)openReview(updated.userId);else setTimeout(closeReview,600)}catch(e){showMessage(e.message||"Unable to update KYC.","error",els.reviewMessage)}finally{button.disabled=false;button.classList.remove("loading")}}
els.table.addEventListener("click",e=>{const b=e.target.closest(".review-button");if(b)openReview(b.dataset.id)});els.documents.addEventListener("click",e=>{const b=e.target.closest(".document-card");if(!b||!b.dataset.url)return;els.largeImage.src=b.dataset.url;els.original.href=b.dataset.url;els.imageModal.classList.add("active");els.imageModal.setAttribute("aria-hidden","false")});document.querySelectorAll(".action-button").forEach(b=>b.addEventListener("click",()=>action(b.dataset.action,b)));els.close.addEventListener("click",closeReview);els.modal.addEventListener("click",e=>{if(e.target===els.modal)closeReview()});els.imageClose.addEventListener("click",()=>els.imageModal.classList.remove("active"));els.imageModal.addEventListener("click",e=>{if(e.target===els.imageModal)els.imageModal.classList.remove("active")});els.search.addEventListener("input",applyFilters);els.status.addEventListener("change",applyFilters);els.sort.addEventListener("change",applyFilters);els.refresh.addEventListener("click",load);els.prev.addEventListener("click",()=>{if(currentPage>1){currentPage--;render()}});els.next.addEventListener("click",()=>{if(currentPage<Math.ceil(filtered.length/pageSize)){currentPage++;render()}});els.logout.addEventListener("click",()=>{if(confirm("Logout from the admin panel?"))logout()});function closeSidebar(){els.sidebar.classList.remove("mobile-open");els.overlay.classList.remove("show");document.body.classList.remove("admin-sidebar-open");els.menu?.setAttribute("aria-expanded","false")}els.menu?.addEventListener("click",()=>{const open=els.sidebar.classList.toggle("mobile-open");els.overlay.classList.toggle("show",open);document.body.classList.toggle("admin-sidebar-open",open);els.menu.setAttribute("aria-expanded",String(open))});els.overlay?.addEventListener("click",closeSidebar);document.addEventListener("keydown",e=>{if(e.key==="Escape"){closeReview();els.imageModal.classList.remove("active");closeSidebar()}});await load();
});