document.addEventListener("DOMContentLoaded",async()=>{
const API_BASE_URL="https://senkupay-api.onrender.com";
const STATUS_ENDPOINT=`${API_BASE_URL}/api/user/kyc/status`;
const SUBMIT_ENDPOINT=`${API_BASE_URL}/api/user/kyc/submit`;
const token=sessionStorage.getItem("token")||localStorage.getItem("token");
if(!token){window.location.replace("login.html");return;}
const message=document.getElementById("kycMessage"),badge=document.getElementById("kycStatusBadge"),documentTypeText=document.getElementById("kycDocumentType"),countryText=document.getElementById("kycCountry"),submittedText=document.getElementById("kycSubmittedAt"),verifiedText=document.getElementById("kycVerifiedAt"),reasonBox=document.getElementById("kycReasonBox"),reasonTitle=document.getElementById("kycReasonTitle"),reasonText=document.getElementById("kycReasonText"),uploadCard=document.getElementById("kycUploadCard"),form=document.getElementById("kycForm"),formTitle=document.getElementById("kycFormTitle"),documentType=document.getElementById("documentType"),documentCountry=document.getElementById("documentCountry"),idFront=document.getElementById("idFront"),idBack=document.getElementById("idBack"),idBackBox=document.getElementById("idBackBox"),selfie=document.getElementById("selfie"),proof=document.getElementById("proofOfAddress"),consent=document.getElementById("kycConsent"),submit=document.getElementById("submitKycBtn"),documentList=document.getElementById("documentList");
function showMessage(text,type="info"){message.hidden=false;message.className=`kyc-message ${type}`;message.textContent=text;window.scrollTo({top:0,behavior:"smooth"})}function clearAuth(){["token","currentUser"].forEach(k=>{sessionStorage.removeItem(k);localStorage.removeItem(k)})}async function request(url,options={}){const response=await fetch(url,{...options,headers:{Accept:"application/json",Authorization:`Bearer ${token}`,...(options.headers||{})}});let data={};try{data=await response.json()}catch{}if(response.status===401||response.status===403){clearAuth();window.location.replace("login.html");throw new Error("Session expired.")}if(!response.ok)throw new Error(data.message||"Request failed.");return data}function formatDate(value){if(!value)return"--";const date=new Date(value);return Number.isNaN(date.getTime())?"--":date.toLocaleString()}function pretty(value){return String(value||"--").replaceAll("_"," ").toLowerCase().replace(/\b\w/g,c=>c.toUpperCase())}
function updateFileName(input,id,empty){const el=document.getElementById(id);el.textContent=input.files?.[0]?.name||empty}[[idFront,"idFrontName","Choose file"],[idBack,"idBackName","Choose file"],[selfie,"selfieName","Choose file"],[proof,"proofOfAddressName","Optional"]].forEach(([input,id,empty])=>input.addEventListener("change",()=>updateFileName(input,id,empty)));
documentType.addEventListener("change",()=>{const passport=documentType.value==="PASSPORT";idBackBox.classList.toggle("hidden",passport);idBack.required=!passport;document.getElementById("idFrontLabel").textContent=passport?"Passport Photo Page":"Document Front"});
function renderDocuments(documents=[]){if(!documents.length){documentList.innerHTML='<p class="empty-text">No documents submitted yet.</p>';return}documentList.innerHTML=documents.map(doc=>`<div class="document-item"><i class="fa-solid fa-file-shield"></i><div><strong>${pretty(doc.type)}</strong><span>${doc.fileName||"Uploaded file"} · ${formatDate(doc.uploadedAt)}</span></div></div>`).join("")}
function renderStatus(kyc={}){const status=String(kyc.status||"NOT_SUBMITTED").toUpperCase();const labels={NOT_SUBMITTED:"Not Submitted",PENDING:"Pending Review",VERIFIED:"Verified",APPROVED:"Verified",REJECTED:"Rejected",REVERIFY_REQUIRED:"Reverification Required",REVERIFICATION_REQUIRED:"Reverification Required",REVOKED:"Revoked"};badge.textContent=labels[status]||pretty(status);badge.className=`status-badge ${status.toLowerCase()}`;documentTypeText.textContent=pretty(kyc.documentType);countryText.textContent=kyc.documentCountry||"--";submittedText.textContent=formatDate(kyc.submittedAt);verifiedText.textContent=formatDate(kyc.verifiedAt);renderDocuments(kyc.documents||[]);const reason=kyc.rejectionReason||kyc.reverificationReason;if(reason){reasonBox.hidden=false;reasonTitle.textContent=kyc.rejectionReason?"Rejection Reason":"Reverification Reason";reasonText.textContent=reason}else reasonBox.hidden=true;if(status==="PENDING"||status==="VERIFIED"||status==="APPROVED"){uploadCard.hidden=true}else{uploadCard.hidden=false;formTitle.textContent=status==="REJECTED"?"Resubmit Verification Documents":status==="REVERIFY_REQUIRED"?"Submit New Verification Documents":"Submit Verification Documents"}}
async function loadStatus(){try{const data=await request(STATUS_ENDPOINT);renderStatus(data.kyc||data.verification||data.data||{})}catch(error){console.error(error);showMessage(error.message||"Unable to load KYC status.","error")}}
form.addEventListener("submit",async event=>{event.preventDefault();if(!documentType.value){showMessage("Select a document type.","error");return}if(!documentCountry.value.trim()){showMessage("Enter the issuing country.","error");return}if(!idFront.files[0]){showMessage("Select the front side of your identity document.","error");return}if(documentType.value!=="PASSPORT"&&!idBack.files[0]){showMessage("Select the back side of your identity document.","error");return}if(!selfie.files[0]){showMessage("Select a selfie image.","error");return}if(!consent.checked){showMessage("Confirm that the documents and information are accurate.","error");return}const data=new FormData();data.append("documentType",documentType.value);data.append("documentCountry",documentCountry.value.trim());data.append("idFront",idFront.files[0]);if(idBack.files[0])data.append("idBack",idBack.files[0]);data.append("selfie",selfie.files[0]);if(proof.files[0])data.append("proofOfAddress",proof.files[0]);submit.disabled=true;submit.innerHTML='<i class="fa-solid fa-spinner fa-spin"></i><span>Uploading...</span>';try{const response=await request(SUBMIT_ENDPOINT,{method:"POST",body:data});showMessage(response.message||"KYC documents submitted successfully.","success");form.reset();await loadStatus()}catch(error){console.error(error);showMessage(error.message||"Unable to submit KYC documents.","error")}finally{submit.disabled=false;submit.innerHTML='<i class="fa-solid fa-cloud-arrow-up"></i><span>Submit KYC Documents</span>'}});
await loadStatus();
});
